### ISSUE TITLE
ReactNative Android Support

### ISSUE THREAD

**Issue by mattapperson** [gorangajic/react-svg-morph#17]
Im lazy and have not tried yet... but one way or another this is an issue...

The ReadMe says iOS only because of no art support on android, but as of earlier this year [thats not true](https://github.com/facebook/react-native/commit/27ac04742ab4665cd529fe63fd68a30db9293b76). So does it work now, and the docs need updating? or is is broken and some compatibility issues exist?

Note: I know I'm lazy and will be testing it later this week if no one responds before then 😊

**Comment by gorangajic** [comment]
It should work but I didn't test it out :)
