### ISSUE TITLE
Add possibility to set "preserveAspectRatio" for svg

### ISSUE THREAD

**Issue by infiman** [gorangajic/react-svg-morph#19]
Hi there,

I have a problem with resizing of my SVG image while using your package. `preserveAspectRatio` attribute allows you to tell from which anchor point to scale, but inside of your implementation this attribute is hardcoded to `preserveAspectRatio="xMidYMid meet"`. I have an idea to create a pull request to fix it and start passing this attribute as a prop. What do you think?

Thank you,
Igor

**Comment by gorangajic** [comment]
should this work?

```jsx
<MorphReplace preserveAspectRatio="...">
...
</MorphReplace>
```

**Comment by infiman** [comment]
https://github.com/gorangajic/react-svg-morph/pull/20

I did fix in this PR.
