### ISSUE TITLE
Basic example doesn't work

### ISSUE THREAD

**Issue by ghost** [gorangajic/react-svg-morph#4]
I copy pasted the example in the readme.
Clicking on the checkbox does not do anything

I'm using react `0.14.2`. how can i trouble shoot this?

**Comment by gorangajic** [comment]
Sorry for that it's missing key prop, that is required. https://github.com/gorangajic/react-svg-morph/commit/7737c3852d271dd0287cedc93a78a0238ecbd533.

**Comment by ghost** [comment]
Oh great that solves it.
Btw, what if i dont want to put an svg? Can i replace the checkbox with a picture for instance?

**Comment by gorangajic** [comment]
svg pictures ?

**Comment by ghost** [comment]
no i mean, i want to replace the checkbox with a facebook picture for instance. So i have to use `img` tag.

**Comment by gorangajic** [comment]
that is not possible, this lib just converts from one svg path to another

**Comment by ghost** [comment]
alright fair enough! Thx a lot though, i love the plugin none the less :)
