### ISSUE TITLE
It's not work

### ISSUE THREAD

**Issue by madwiki** [gorangajic/react-svg-morph#9]
I tried it in generator-react-webpack.It's not work.Thank you!

Properties like width and height are working,but neither animation nor icon changes while changing states.

**Comment by gorangajic** [comment]
I will need more info, like 
- are you trying to run that using react-dom or react-native
- code example/sample where it's not working

**Comment by nuoyz** [comment]
Same situation with redux

**Comment by gorangajic** [comment]
Maybe you are missing `key` props. I have updated Readme https://github.com/gorangajic/react-svg-morph/commit/b0b0b59cf72f4b9af5d2b529adfda89e7a8d88ab

**Comment by madwiki** [comment]
It works! Thank you!

**Comment by gorangajic** [comment]
You are welcome
